# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('Doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('Contact', models.BigIntegerField()),
                ('Email', models.CharField(max_length=30)),
                ('Specialization', models.CharField(max_length=30)),
                ('Degree', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=8)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
