# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('Contact', models.IntegerField(max_length=12)),
                ('Gender', models.CharField(max_length=8)),
                ('Category', models.CharField(max_length=20)),
            ],
        ),
    ]
