# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20171028_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=20)),
                ('Doctor_Name', models.CharField(max_length=20)),
                ('AppointmentDate', models.DateField()),
                ('AppointmentTime', models.TimeField()),
                ('Disease', models.CharField(max_length=20)),
                ('Lastvisited', models.DateField()),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
