# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Patient_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
