# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_appointment_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Patient_id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
