# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20171108_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Category',
        ),
    ]
