# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_signup_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Password',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
