# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_signup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Lastvisited',
        ),
    ]
