# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_signup_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Age',
        ),
    ]
