# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_remove_appointment_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pid',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
